

export const leadsData = [
  {
    id: 1,
    name: "Ivy Brown",
    email: "ivyb@example.com",
    phone: "012-345-6789",
    secondphone: "901-234-5678",
    address: "123 Willow St, Anystate, USA",
    status: "inactive",
    priority: "low",
    stage: "qualified",
    collaborators: ["Henry White", "Jack Gray"],
    branchcode: "b1",
    remainder: "Verify qualification criteria",
    source: "seo",
    datetimeadded: "2024-06-02T11:30:00Z",
    comments: [
      {
        comment: "Passed initial qualification.",
        user: "Henry White",
        datetime: "2024-06-02T11:35:00Z",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janes@example.com",
    phone: "123-456-7890",
    secondphone: "987-654-3210",
    address: "456 Maple St, Anystate, USA",
    status: "active",
    priority: "medium",
    stage: "prospect",
    collaborators: ["Jack Gray"],
    branchcode: "b2",
    remainder: "Follow-up in 3 days",
    source: "email campaign",
    datetimeadded: "2024-06-03T09:20:00Z",
    comments: [
      {
        comment: "Scheduled follow-up call.",
        user: "Jack Gray",
        datetime: "2024-06-03T09:30:00Z",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alicej@example.com",
    phone: "234-567-8901",
    secondphone: "876-543-2109",
    address: "789 Oak St, Anystate, USA",
    status: "inactive",
    priority: "high",
    stage: "negotiation",
    collaborators: ["Henry White"],
    branchcode: "b3",
    remainder: "Send contract",
    source: "referral",
    datetimeadded: "2024-06-04T10:15:00Z",
    comments: [
      {
        comment: "Preparing contract for client.",
        user: "Henry White",
        datetime: "2024-06-04T10:20:00Z",
      },
    ],
  },
  {
    id: 4,
    name: "Bob Martin",
    email: "bobm@example.com",
    phone: "345-678-9012",
    secondphone: "765-432-1098",
    address: "101 Pine St, Anystate, USA",
    status: "active",
    priority: "low",
    stage: "reprospect",
    collaborators: ["Jack Gray"],
    branchcode: "b1",
    remainder: "Review documents",
    source: "social media",
    datetimeadded: "2024-06-05T11:00:00Z",
    comments: [
      {
        comment: "Documents under review.",
        user: "Jack Gray",
        datetime: "2024-06-05T11:05:00Z",
      },
    ],
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlied@example.com",
    phone: "456-789-0123",
    secondphone: "654-321-0987",
    address: "202 Birch St, Anystate, USA",
    status: "inactive",
    priority: "medium",
    stage: "prospect",
    collaborators: ["Henry White", "Jane Smith"],
    branchcode: "b2",
    remainder: "Check in next week",
    source: "webinar",
    datetimeadded: "2024-06-06T12:30:00Z",
    comments: [
      {
        comment: "Waiting for client response.",
        user: "Henry White",
        datetime: "2024-06-06T12:35:00Z",
      },
    ],
  },
  {
    id: 6,
    name: "David Lee",
    email: "davidl@example.com",
    phone: "567-890-1234",
    secondphone: "543-210-9876",
    address: "303 Cedar St, Anystate, USA",
    status: "active",
    priority: "high",
    stage: "nurture",
    collaborators: ["Alice Johnson"],
    branchcode: "b3",
    remainder: "Finalize terms",
    source: "direct mail",
    datetimeadded: "2024-06-07T14:00:00Z",
    comments: [
      {
        comment: "Negotiating final terms.",
        user: "Alice Johnson",
        datetime: "2024-06-07T14:05:00Z",
      },
    ],
  },
  {
    id: 7,
    name: "Evelyn Clark",
    email: "evelync@example.com",
    phone: "678-901-2345",
    secondphone: "432-109-8765",
    address: "404 Spruce St, Anystate, USA",
    status: "inactive",
    priority: "low",
    stage: "qualified",
    collaborators: ["Bob Martin"],
    branchcode: "b1",
    remainder: "Contact next month",
    source: "SEO",
    datetimeadded: "2024-06-08T08:45:00Z",
    comments: [
      {
        comment: "Will contact next month.",
        user: "Bob Martin",
        datetime: "2024-06-08T08:50:00Z",
      },
    ],
  },
  {
    id: 8,
    name: "Frank Green",
    email: "frankg@example.com",
    phone: "789-012-3456",
    secondphone: "321-098-7654",
    address: "505 Elm St, Anystate, USA",
    status: "active",
    priority: "medium",
    stage: "prospect",
    collaborators: ["Charlie Davis"],
    branchcode: "b2",
    remainder: "Send proposal",
    source: "email campaign",
    datetimeadded: "2024-06-09T09:10:00Z",
    comments: [
      {
        comment: "Proposal sent to client.",
        user: "Charlie Davis",
        datetime: "2024-06-09T09:15:00Z",
      },
    ],
  },
  {
    id: 9,
    name: "Grace Hill",
    email: "graceh@example.com",
    phone: "890-123-4567",
    secondphone: "210-987-6543",
    address: "606 Ash St, Anystate, USA",
    status: "inactive",
    priority: "high",
    stage: "opportunity",
    collaborators: ["David Lee"],
    branchcode: "b3",
    remainder: "Confirm meeting",
    source: "referral",
    datetimeadded: "2024-06-10T10:20:00Z",
    comments: [
      {
        comment: "Meeting scheduled for next week.",
        user: "David Lee",
        datetime: "2024-06-10T10:25:00Z",
      },
    ],
  },
  {
    id: 10,
    name: "Hannah King",
    email: "hannahk@example.com",
    phone: "901-234-5678",
    secondphone: "109-876-5432",
    address: "707 Fir St, Anystate, USA",
    status: "active",
    priority: "low",
    stage: "qualified",
    collaborators: ["Evelyn Clark"],
    branchcode: "b1",
    remainder: "Send follow-up email",
    source: "social media",
    datetimeadded: "2024-06-11T11:40:00Z",
    comments: [
      {
        comment: "Follow-up email sent.",
        user: "Evelyn Clark",
        datetime: "2024-06-11T11:45:00Z",
      },
    ],
  },
];

